version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf

  api:
    build: /Tasks/hello_world
    ports:
      - "8080:80"


  redis-server:
    image: redis:alpine

  db:
    image: postgres:alpine
    restart: "always"

  # vote:
  #   image: voting-app
  #   ports:
  #     - 5000:80
  #   depends_on:
  #     - redis
  #   networks:
  #     - backend
  #     - frontend

  # result:
  #   image: result-app
  #   ports:
  #     - 5001:80
  #   links:
  #     - db
  #   networks:
  #     - backend
  #     - frontend

  # worker:
  #   image: worker
  #   links:
  #     - redis
  #     - db
  #   networks:
  #     - backend

networks:
  backend:
  frontend: