version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    networks:
      - backend-network

  api:
    build: /Tasks/hello_world
    ports:
      - "8080:80"
    networks:
      - backend-network

  postgres:
    image: postgres:alpine
    restart: "always"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  adminer_container:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8081:8080
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 

volumes:
  postgres_data: