version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - ${WEB_PORTS:-8876:80}
    volumes:
      - ./public:/var/www/public
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - backend-network
    depends_on:
      - postgres
      - api

  api:
    build: ./images/php
    volumes:
      - /www:/var/www
    networks:
      - backend-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine
    restart: "always"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
    ports:
      - ${POSTGRES_PORTS:-5432:5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  adminer_container:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - ${ADMINER_PORTS:-8081:8080}
    networks:
      - backend-network
    depends_on:
      - postgres

networks:
  backend-network:
    driver: bridge 

volumes:
  postgres_data: